### ISSUE TITLE
WebSocket is not defined

### ISSUE THREAD

**Issue by Ezharjan** [jjxxs/websocket-ts#11]
While I was using `websocket-ts` in my project, I met the problem below:
```bash
   this.websocket = new WebSocket(this.url, this.protocols); // create new socket and attach handlers
                             ^

ReferenceError: WebSocket is not defined
    at Websocket.tryConnect (D:\4-th_Grade\1_GraduationProj\LiveRequestServer\node_modules\websocket-ts\lib\websocket.js:80:30)
    at new Websocket (D:\4-th_Grade\1_GraduationProj\LiveRequestServer\node_modules\websocket-ts\lib\websocket.js:26:14)
    at WebsocketBuilder.build (D:\4-th_Grade\1_GraduationProj\LiveRequestServer\node_modules\websocket-ts\lib\websocketBuilder.js:57:19)
    at Object.<anonymous> (D:\4-th_Grade\1_GraduationProj\LiveRequestServer\dist\friend\wsServer.js:20:6)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! liverequestserver@1.0.0 friend: `node dist/friend/wsServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the liverequestserver@1.0.0 friend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

<br>

My code is:
```js
import { WebsocketBuilder } from 'websocket-ts';

export enum WebsocketEvents {
    open = 'open',          // Connection is opened or re-opened
    close = 'close',        // Connection is closed
    error = 'error',        // An error occurred
    message = 'message',    // A message was received
    retry = 'retry'         // A try to re-connect is made
}

const ws = new WebsocketBuilder('ws://localhost:43999')
    .onOpen((i, ev) => { console.log("opened") })
    .onClose((i, ev) => { console.log("closed") })
    .onError((i, ev) => { console.log("error") })
    .onMessage((i, ev) => { console.log("message") })
    .onRetry((i, ev) => { console.log("retry") })
    .build();

console.log("done!");
ws.send("hello world!!!!");
```
I first compiled it to JavaScript and then run `node wsServer.js`, it compiled well but met problems.
Also, I can't find any `examples` in this repositry. May you show me some example codes on using your npm module correctly in a TypeScript based project?

**Comment by jjxxs** [comment]
Hi there! This websocket is meant to be used from within browser-applications, e.g. your web-project. It shouldn't be used for node-projects, hence the complain about some missing definitions. I recommend you look for a different library if you want to create a nodejs-app. Cheers
