### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by gocpplua** [jjxxs/websocket-ts#13]
my node version is:v14.16.1

step 1:
`npm install websocket-ts`

step 2: create index.ts
import { WebsocketBuilder } from 'websocket-ts';

const ws = new WebsocketBuilder('ws://localhost:42421')
    .onOpen((i, ev) => { console.log("opened") })
    .onClose((i, ev) => { console.log("closed") })
    .onError((i, ev) => { console.log("error") })
    .onMessage((i, ev) => { console.log("message") })
    .onMessage((i, ev) => { i.send(ev.data) })
    .onRetry((i, ev) => { console.log("retry") })
    .build();

step3:
`tsc index.ts`

step4:
`node index.js`

then there is a error:
GOCPPLUA\cc@cn0314000510l:/data/chenqi/docker_node$ node index.js 
/data/XXXX/docker_node/node_modules/websocket-ts/lib/websocket.js:80
        this.websocket = new WebSocket(this.url, this.protocols); // create new socket and attach handlers
                             ^

ReferenceError: WebSocket is not defined
    at Websocket.tryConnect (/data/XXXX/docker_node/node_modules/websocket-ts/lib/websocket.js:80:30)
    at new Websocket (/data/XXXX/docker_node/node_modules/websocket-ts/lib/websocket.js:26:14)
    at WebsocketBuilder.build (/data/XXXX/docker_node/node_modules/websocket-ts/lib/websocketBuilder.js:57:19)
    at Object.<anonymous> (/data/XXXX/docker_node/index.js:11:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by jjxxs** [comment]
Thanks for reporting. This project is meant to be used from within the browser, e.g. it's a wrapper for the browser-provided websocket. That's why Node is complaining. I recommend to use a different project that fits your needs.
